### ISSUE TITLE
Unsupported project types are crashing the tool

### ISSUE THREAD

**Issue by mungojam** [hvanbakel/CsprojToVs2017#173]
I take it the intended behaviour is that the tool will report an error but continue to run for supported project types. That seems to be the ideal since people may be running a batch conversion across many folders knowing that they might have some unsupported projects.

Anyway, when I run against the full Force.com example, using `Project2015To2017.Console.exe .\` at the root of the repository from commit: 7b0d1fc24864ad8026d93579779d19c95b9cdfe9 I get:

> info No nuspec found, skipping package configuration.
fail This project type is not supported for conversion.
info No nuspec found, skipping package configuration.
fail TargetFramework cannot be determined from project file. The scenario is not supported and highly bug-prone.

> Unhandled Exception: System.NotSupportedException: OutputType AppContainerExe is not supported.
   at Project2015To2017.Reading.ProjectPropertiesReader.ToApplicationType(String outputType)
   at Project2015To2017.Reading.ProjectPropertiesReader.Read(Project project)
   at Project2015To2017.Reading.ProjectReader.Read(FileInfo projectFile)
   at Project2015To2017.ProjectConverter.ProcessFile(FileInfo file, Solution solution, ProjectReference reference)
   at Project2015To2017.ProjectConverter.<Convert>d__5.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Project2015To2017.Console.Program.ConvertProject(Options options)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Project2015To2017.Console.Program.Main(String[] args)

This happens with the released RC version and the new PR

The result is that nothing gets converted

**Comment by hvanbakel** [comment]
This is just a bug, I had to look up what it was and:
```
If you use the -target:appcontainerexe compiler option, the compiler creates a Windows executable (.exe) file that must be run in an app container. This option is equivalent to -target:winexe but is designed for Windows 8.x Store apps.
```

So that's just an addition that we need to make, that would've crashed ever since v.1 I guess.
