### ISSUE TITLE
OutputType WinExe is not supported

### ISSUE THREAD

**Issue by Deathofdemigod** [hvanbakel/CsprojToVs2017#23]
Unhandled Exception: System.NotSupportedException: OutputType WinExe is not supported.
   at Project2015To2017.ProjectPropertiesTransformation.ToApplicationType(String outputType)
   at Project2015To2017.ProjectPropertiesTransformation.TransformAsync(XDocument projectFile, DirectoryInfo projectFolder, Project definition)
   at Project2015To2017.Program.<>c__DisplayClass1_0.<Main>b__0(ITransformation t)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Project2015To2017.Program.Main(String[] args)

**Comment by hvanbakel** [comment]
Should be fixed on latest version. Will create a new build once I can get hold of a box to do so.
