### ISSUE TITLE
Exception when Nuspec is found

### ISSUE THREAD

**Issue by dampee** [hvanbakel/CsprojToVs2017#82]
Hi 
I got an exception when converting.

```
Multiple project files found under directory ..\[myfolder]
Found nuget reference to Autofac, version 4.6.2.
Found nuget reference to BCrypt.Net-Next, version 2.1.3.
Found nuget reference to Newtonsoft.Json, version 9.0.1.
No nuspec found, skipping package configuration.
Reading assembly info from [myFolder]\Properties\AssemblyInfo.cs.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Project2015To2017.Transforms.NugetPackageTransformation.PopulatePlaceHolders(PackageConfiguration rawPackageConfig, AssemblyAttributes assemblyAttributes)
   at Project2015To2017.Transforms.NugetPackageTransformation.Transform(Project definition, IProgress`1 progress)
   at Project2015To2017.ProjectConverter.ProcessFile(String filePath, IProgress`1 progress)
   at Project2015To2017.ProjectConverter.<Convert>d__1.MoveNext()
   at Project2015To2017.Console.Program.Main(String[] args)
```

**Comment by dampee** [comment]
I forgot to mention it's in the latest version.  I checked it, and the new version fixes the issue.  

Very nice tool.  Well done!

**Comment by ud09** [comment]
Although this seems fixed in the code,  the tool installed globally via 
dotnet tool install --global Project2015To2017.Migrate2019.Tool 
still throws this error.
